// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetARPEntries() {
  return window['go']['network']['NetworkDashboardService']['GetARPEntries']();
}

export function GetLocalIP() {
  return window['go']['network']['NetworkDashboardService']['GetLocalIP']();
}

export function GetNetworkConnections() {
  return window['go']['network']['NetworkDashboardService']['GetNetworkConnections']();
}

export function GetNetworkInterfaces() {
  return window['go']['network']['NetworkDashboardService']['GetNetworkInterfaces']();
}

export function GetPublicIP() {
  return window['go']['network']['NetworkDashboardService']['GetPublicIP']();
}

export function Init() {
  return window['go']['network']['NetworkDashboardService']['Init']();
}

export function StartPacketCapture(arg1, arg2, arg3) {
  return window['go']['network']['NetworkDashboardService']['StartPacketCapture'](arg1, arg2, arg3);
}

export function StopPacketCapture() {
  return window['go']['network']['NetworkDashboardService']['StopPacketCapture']();
}
