// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';

export function GetARPEntries():Promise<Array<network.ARPEntry>>;

export function GetLocalIP():Promise<string>;

export function GetNetworkConnections():Promise<Array<network.NetworkConnection>>;

export function GetNetworkInterfaces():Promise<Array<network.NetworkInterface>>;

export function GetPublicIP():Promise<string>;

export function Init():Promise<void>;

export function StartPacketCapture(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function StopPacketCapture():Promise<void>;
