// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPublicIP() {
  return window['go']['network']['PublicIPService']['GetPublicIP']();
}

export function GetPublicIPInfo() {
  return window['go']['network']['PublicIPService']['GetPublicIPInfo']();
}
