// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterDesktopEntry() {
  return window['go']['backend']['SetupService']['RegisterDesktopEntry']();
}
