// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateReport() {
  return window['go']['report']['ReportService']['GenerateReport']();
}

export function SaveReport(arg1, arg2) {
  return window['go']['report']['ReportService']['SaveReport'](arg1, arg2);
}
