// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateReport():Promise<string>;

export function SaveReport(arg1:string,arg2:string):Promise<void>;
