// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['appsvc']['App']['Greet'](arg1);
}

export function Startup(arg1) {
  return window['go']['appsvc']['App']['Startup'](arg1);
}
