// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';
import {context} from '../models';

export function GetCaptureTemplates():Promise<Array<network.CaptureTemplate>>;

export function SaveCaptureTemplate(arg1:network.CaptureTemplate):Promise<void>;

export function StartPacketCapture(arg1:string,arg2:string,arg3:number):Promise<void>;

export function StopPacketCapture():Promise<void>;

export function WailsInit(arg1:context.Context):Promise<void>;
