// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCaptureTemplates() {
  return window['go']['tools']['AdvancedNetworkToolsService']['GetCaptureTemplates']();
}

export function SaveCaptureTemplate(arg1) {
  return window['go']['tools']['AdvancedNetworkToolsService']['SaveCaptureTemplate'](arg1);
}

export function StartPacketCapture(arg1, arg2, arg3) {
  return window['go']['tools']['AdvancedNetworkToolsService']['StartPacketCapture'](arg1, arg2, arg3);
}

export function StopPacketCapture() {
  return window['go']['tools']['AdvancedNetworkToolsService']['StopPacketCapture']();
}

export function WailsInit(arg1) {
  return window['go']['tools']['AdvancedNetworkToolsService']['WailsInit'](arg1);
}
