// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNetworkInterfaces() {
  return window['go']['tools']['NetworkToolsService']['GetNetworkInterfaces']();
}

export function Ping(arg1) {
  return window['go']['tools']['NetworkToolsService']['Ping'](arg1);
}

export function Traceroute(arg1) {
  return window['go']['tools']['NetworkToolsService']['Traceroute'](arg1);
}
