// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';
import {tools} from '../models';

export function GetNetworkInterfaces():Promise<Array<network.NetworkInterface>>;

export function Ping(arg1:string):Promise<tools.PingResult>;

export function Traceroute(arg1:string):Promise<Array<tools.TracerouteHop>>;
